version: '3.8'

services:
  db:
    container_name: aicademy-workshop_db
    image: postgres
    restart: always
    ports:
      - 1110:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_aicademy-workshop:/var/lib/postgresql/data
volumes:
  db_data_aicademy-workshop:
